### ISSUE TITLE
Cast waterbodies to single-part before assigning Index ID

### ISSUE THREAD

**Issue by abock80** [DOI-USGS/hydroloom#34]
While working with some of the point interbasin transfers and trying to index to waterbodies/flowlines, noticed flowlines are correct, but waterbodies are not.  We believe the error is due to waterbodies being coerced to singlepart after the feature index identifiers are derived.  Moving the "to_singlepart" function ahead of the feature index attribution fixed this error.

https://github.com/DOI-USGS/hydroloom/pull/33

**Comment by dblodgett-usgs** [comment]
Thanks for this -- I want to make sure this doesn't have any weird side affects. Will pull it down and double check a few things.

**Comment by dblodgett-usgs** [comment]
@abock80 do you have a waterbody polygon that is actually a multipolygon that I could use for testing? My test data is all single polygons.

**Comment by abock80** [comment]
@dblodgett-usgs - yea I'll try to dig one up.  Long story short (explain this PM), Laura had been using the old "incorrect" reference_waterbody set, but I think it's an error that may (?) come up.

**Comment by dblodgett-usgs** [comment]
hmmm... ok. Maybe the function should check if waterbodies are true multipart polygons and just error if they are? The function is not designed to support multipolygons and I'm concerned that it would be a lot of complexity to get it right for a very edge case situation.

**Comment by abock80** [comment]
I'd be down with kicking out the error and having the user figure it out
