### ISSUE TITLE
navigate_hydro_network finds duplicate id for starting catchment 

### ISSUE THREAD

**Issue by mewieczo** [DOI-USGS/hydroloom#49]
Using navigate_hydro_network to find upstream and downstream SW gages and get the following error:
 **Error in get_start_row(x, id) : 
  Found duplicate id for starting catchment. Duplicate rows in network?**

Here is a sample script that reproduces this error:

`library(hydroloom)
gages <- sf::read_sf("https://www.hydroshare.org/resource/3295a17b4cc24d34bd6a5c5aaf753c50/data/contents/ref_gages.gpkg")
provider_id <- "10142000"

gage <- gages[gages$provider_id == provider_id,]
ut <- hydroloom::navigate_hydro_network(vaa, gage$nhdpv2_COMID, mode = "UT", distance = 9999)
dt <- hydroloom::navigate_hydro_network(vaa, gage$nhdpv2_COMID, mode = "DM", distance = 9999)

network_gages <- gages[gages$nhdpv2_COMID %in% c(ut, dt),]`

**Comment by dblodgett-usgs** [comment]
Sorry it took me a while to get back to this. Turns out that the gage you are trying to use has an NA COMID. It doesn't have a network link. I'll put in a more informative error message.

**Comment by dblodgett-usgs** [comment]
Looking into why this was missing from reference gages... there's no nhdplusv2 data for the creek it's on. 

![image](https://github.com/user-attachments/assets/060664b0-d3db-4383-90bb-721dadf45c09)
